"""
spill_classifier.py
=====================
Loads the trained model from spill_model_weights.py (generated by
train_spill_classifier.py) and runs prediction using only numpy -- no
scikit-learn needed at runtime, so this is safe to run on the Pi without
installing sklearn there.

train_spill_classifier.py tries both a Logistic Regression and a Random
Forest and exports whichever tested more accurately, so this file
supports both MODEL_TYPEs. Either way, prediction here is pure Python +
numpy: a straight dot-product + sigmoid for logistic regression, or a
plain if/else tree walk for a random forest.

Usage:
    from spill_classifier import predict_silver, extract_features
    feats = extract_features(roi)          # roi = a BGR image region
    is_silver, confidence = predict_silver(feats)
"""

import numpy as np
import cv2

try:
    import spill_model_weights as _w
except ImportError:
    raise ImportError(
        "spill_model_weights.py not found. Run collect_spill_samples.py then "
        "train_spill_classifier.py first (on your laptop), then copy the "
        "generated spill_model_weights.py next to this file."
    )

MODEL_TYPE = getattr(_w, "MODEL_TYPE", "logistic_regression")
FEATURE_NAMES = _w.FEATURE_NAMES


def extract_features(roi):
    """roi is a BGR image region (e.g. frame[y1:y2, x1:x2])."""
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)

    b, g, r = cv2.mean(roi)[:3]
    h, s, v = cv2.mean(hsv)[:3]
    brightness = float(np.mean(gray))
    std_dev = float(np.std(gray))
    max_val = float(np.max(gray))
    min_val = float(np.min(gray))

    return {
        "R": r, "G": g, "B": b,
        "H": h, "S": s, "V": v,
        "brightness": brightness,
        "std_dev": std_dev,
        "max": max_val, "min": min_val,
        "range": max_val - min_val,
    }


def _predict_logistic(x):
    mean = np.array(_w.MEAN)
    scale = np.array(_w.SCALE)
    weights = np.array(_w.WEIGHTS)

    x_scaled = (x - mean) / scale
    z = np.dot(weights, x_scaled) + _w.BIAS
    prob_silver = 1.0 / (1.0 + np.exp(-z))   # sigmoid
    return float(prob_silver)


def _walk_tree(tree, x):
    """Walk one exported decision tree (plain dict of arrays) for one sample."""
    node = 0
    feature = tree["feature"]
    threshold = tree["threshold"]
    left = tree["children_left"]
    right = tree["children_right"]

    while left[node] != -1:   # -1 marks a leaf in sklearn's tree_ arrays
        if x[feature[node]] <= threshold[node]:
            node = left[node]
        else:
            node = right[node]

    return tree["leaf_prob_silver"][node]


def _predict_random_forest(x):
    probs = [_walk_tree(tree, x) for tree in _w.TREES]
    return float(np.mean(probs))


def predict_silver(feats):
    """
    feats: dict from extract_features().
    Returns (is_silver: bool, confidence: float 0-1).
    """
    x = np.array([feats[name] for name in FEATURE_NAMES], dtype=np.float64)

    if MODEL_TYPE == "random_forest":
        prob_silver = _predict_random_forest(x)
    else:
        prob_silver = _predict_logistic(x)

    is_silver = prob_silver >= 0.5
    confidence = prob_silver if is_silver else (1.0 - prob_silver)
    return bool(is_silver), float(confidence)
