"""
train_spill_classifier.py
===========================
Step 2 of the trained spill-tape classifier. Reads spill_samples.csv
(built with collect_spill_samples.py / collect_spill_samples_pi.py),
trains TWO candidate models -- Logistic Regression and a Random Forest --
picks whichever scores higher on a held-out test split, and writes the
winner out as a plain Python file (spill_model_weights.py) with just
numbers, no scikit-learn needed to USE the model afterwards. That file
is what actually gets copied to the Pi; scikit-learn is only needed
here, on your laptop, for training.

Why try both: Logistic Regression can only draw a straight-line boundary
through the feature space. Texture-vs-color separation (tape's crinkled
highlights vs a flat tile) isn't always linearly separable, so a Random
Forest -- which can carve up the feature space into arbitrary regions --
sometimes does meaningfully better on the exact same data.

Run on your laptop:
    pip install scikit-learn numpy
    python train_spill_classifier.py

Prints both models' test accuracy so you can see which one actually won
and by how much, plus a confusion matrix for the winner.
"""

import csv
import os

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

CSV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "spill_samples.csv")
OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "spill_model_weights.py")

FEATURE_NAMES = ["R", "G", "B", "H", "S", "V", "brightness", "std_dev", "max", "min", "range"]

RANDOM_STATE = 42
N_TREES = 50
MAX_DEPTH = 5   # keep trees shallow -- less likely to overfit a small dataset,
                 # and keeps the exported file small


def export_logistic(model, scaler):
    return {
        "MODEL_TYPE": "logistic_regression",
        "FEATURE_NAMES": FEATURE_NAMES,
        "MEAN": scaler.mean_.tolist(),
        "SCALE": scaler.scale_.tolist(),
        "WEIGHTS": model.coef_[0].tolist(),
        "BIAS": float(model.intercept_[0]),
    }


def export_tree(tree):
    """Export one sklearn DecisionTree's internal arrays as plain lists."""
    t = tree.tree_
    # value[node][0] = [count_class_0, count_class_1] -- convert to a
    # probability of class 1 (silver) at each leaf.
    leaf_prob_silver = []
    for node in range(t.node_count):
        counts = t.value[node][0]
        total = counts[0] + counts[1]
        leaf_prob_silver.append(float(counts[1] / total) if total > 0 else 0.0)

    return {
        "feature": [int(x) for x in t.feature],
        "threshold": [float(x) for x in t.threshold],
        "children_left": [int(x) for x in t.children_left],
        "children_right": [int(x) for x in t.children_right],
        "leaf_prob_silver": leaf_prob_silver,
    }


def export_random_forest(model):
    return {
        "MODEL_TYPE": "random_forest",
        "FEATURE_NAMES": FEATURE_NAMES,
        "TREES": [export_tree(est) for est in model.estimators_],
    }


def write_weights_file(data):
    with open(OUT_PATH, "w") as f:
        f.write('"""\nAuto-generated by train_spill_classifier.py -- do not edit by hand.\n')
        f.write("Retrain and regenerate this file instead if you collect more samples.\n\"\"\"\n\n")
        for key, value in data.items():
            f.write(f"{key} = {value!r}\n")


def main():
    if not os.path.exists(CSV_PATH):
        print(f"No {CSV_PATH} found. Run collect_spill_samples.py first.")
        return

    X, y = [], []
    with open(CSV_PATH, newline="") as f:
        for row in csv.DictReader(f):
            X.append([float(row[name]) for name in FEATURE_NAMES])
            y.append(1 if row["label"] == "silver" else 0)

    X = np.array(X)
    y = np.array(y)

    n_silver = int(np.sum(y == 1))
    n_tile = int(np.sum(y == 0))
    print(f"Loaded {len(y)} samples: silver={n_silver}  tile={n_tile}")
    if n_silver < 10 or n_tile < 10:
        print("WARNING: fewer than 10 samples of one class. Collect more with "
              "collect_spill_samples.py for a reliable model.")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=RANDOM_STATE,
        stratify=y if min(n_silver, n_tile) > 1 else None
    )

    # --- Candidate 1: Logistic Regression ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    logreg = LogisticRegression(max_iter=1000, class_weight="balanced")
    logreg.fit(X_train_scaled, y_train)
    logreg_acc = accuracy_score(y_test, logreg.predict(X_test_scaled))

    # --- Candidate 2: Random Forest ---
    forest = RandomForestClassifier(
        n_estimators=N_TREES, max_depth=MAX_DEPTH,
        class_weight="balanced", random_state=RANDOM_STATE
    )
    forest.fit(X_train, y_train)   # trees don't need scaled features
    forest_acc = accuracy_score(y_test, forest.predict(X_test))

    print(f"\nLogistic Regression test accuracy: {logreg_acc*100:.1f}%")
    print(f"Random Forest test accuracy:       {forest_acc*100:.1f}%")

    if forest_acc >= logreg_acc:
        print("\n>>> Random Forest wins -- exporting that model.")
        y_pred = forest.predict(X_test)
        data = export_random_forest(forest)
    else:
        print("\n>>> Logistic Regression wins -- exporting that model.")
        y_pred = logreg.predict(X_test_scaled)
        data = export_logistic(logreg, scaler)

    print("Confusion matrix (rows=actual, cols=predicted) [tile, silver]:")
    print(confusion_matrix(y_test, y_pred))

    write_weights_file(data)
    print(f"\nWrote trained weights to {OUT_PATH}")
    print("Copy this file to the Pi alongside spill_classifier.py.")


if __name__ == "__main__":
    main()
